{
  inputs,
  username,
  ...
}:

{
  imports = [ inputs.nix-homebrew.darwinModules.nix-homebrew ];

  # nix-homebrew owns the Homebrew *installation*: it creates /opt/homebrew and
  # points it at a pinned Homebrew/brew checkout from the Nix store. Homebrew's
  # own curl-into-bash installer is never run, and `brew update-self` is disabled.
  nix-homebrew = {
    enable = true;
    user = username;

    # Apple Silicon only. Setting this would additionally provision an
    # x86_64 prefix under /usr/local and require Rosetta.
    enableRosetta = false;

    # Taps stay mutable, which keeps Homebrew on its JSON metadata API. Pinning
    # homebrew-core and homebrew-cask as flake inputs is the fully reproducible
    # alternative, but it drags hundreds of megabytes through the store on every
    # update for very little practical benefit here.
    mutableTaps = true;
  };

  # nix-darwin owns *what* Homebrew installs, via a generated Brewfile.
  homebrew = {
    enable = true;

    casks = [
      # Karabiner-Elements provides Neo2 layers 3-6. The cask is the right
      # mechanism: it installs the vendor-signed pkg at the vendor's paths,
      # which is what the DriverKit virtual-HID system extension needs in order
      # to be approvable. nixpkgs lags upstream and nix-darwin's
      # `services.karabiner-elements` has been broken since Karabiner 15.
      "karabiner-elements"

      # Terminal. Not available from nixpkgs on aarch64-darwin, and the
      # official Neo2 Karabiner rules already whitelist com.mitchellh.ghostty
      # for layer-4 Home/End.
      "ghostty"

      # Git UI. Proprietary macOS app, so Homebrew is the only sane channel;
      # it reads the identity generated by modules/home/git.nix.
      "fork"

      # Browsers. Deliberately casks even though nixpkgs can build Brave (and
      # Firefox) for aarch64-darwin: a browser has to take security fixes on the
      # vendor's schedule, not on this flake's `nix flake update` cadence.
      #
      # Zen is the daily driver, Gecko-based and currently at exact parity with
      # Firefox stable. Brave is the Chromium one, needed because the omp
      # browser relay is a Chrome extension and cannot load into Gecko.
      "zen"
      "brave-browser"

      # Secure Enclave SSH agent. Not in nixpkgs for darwin, and it has to be a
      # signed app bundle anyway to get Secure Enclave and Touch ID entitlements.
      "secretive"

      # Password manager. The cask build does bundle the Safari extension, as
      # `Contents/PlugIns/safari.appex` (`com.bitwarden.desktop.safari`), so no
      # Mac App Store copy is needed for it. Extensions for Zen and Brave come
      # from their own browser stores and are not manageable from here.
      "bitwarden"

      # Editor. nixpkgs has zed-editor for darwin, but Zed ships very
      # frequently and its own updater expects the vendor bundle; the cask
      # keeps us on the release cadence the editor is built around.
      "zed"

      "discord"

      # Tasks and calendar.
      "ticktick"

      # Window management. The paid Pro build, whose bundle identifier is still
      # `com.knollsoft.Hookshot` from when it was called Hookshot -- that is the
      # domain to use for any `defaults` tweaking. Licensing is a one-off
      # purchase activated by pasting a code into the app, so it cannot be
      # declared here; see the manual steps in the README.
      "rectangle-pro"

      # Windows compatibility layer. All game-related work goes through
      # CrossOver bottles rather than native Steam, so no Steam cask.
      "crossover"
    ];

    onActivation = {
      # Uninstall anything not declared above. Deliberately not "zap", which
      # would also delete ~/.config/karabiner.
      cleanup = "uninstall";
      autoUpdate = true;
      upgrade = false;
    };
  };
}
