[credentials]
recipient = "age1nkezccfyk8xrj6xnwppr0cca9mm80j2gkuxndseamfq76px2a52s98vn93"
identity = ".config/sops/age/keys.txt"
directory = ".config/credentials"
names = ["fastmail-token", "cloudflare-dns-token", "cloudflare-workers-token"]
